# Generated by Django 4.1.3 on 2022-12-03 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MiracleArt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pin',
            options={'verbose_name': 'Пин', 'verbose_name_plural': 'Пины'},
        ),
        migrations.AlterModelOptions(
            name='pincategory',
            options={'verbose_name': 'Категорию Пина', 'verbose_name_plural': 'Категории Пинов'},
        ),
        migrations.AlterField(
            model_name='pin',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MiracleArt.pincategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='img',
            field=models.ImageField(upload_to='images/', verbose_name='Пин/Картинка'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='slug',
            field=models.SlugField(default='', verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='text',
            field=models.TextField(blank=True, max_length=90, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='pincategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pincategory',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название'),
        ),
    ]
