# Generated by Django 4.1.3 on 2022-12-16 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiracleArt', '0002_alter_pin_options_alter_pincategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pincategory',
            options={},
        ),
    ]
